package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	graph "assignment/internal/graph/generate"
	"assignment/internal/graph/model"
	"context"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.UserResponse, error) {
	panic("not implemented")
}

// UpdateUser implements graph.MutationResolver.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UserInput) (*model.UserResponse, error) {
	panic("unimplemented")
}

// DeleteUser implements graph.MutationResolver.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (*model.Response, error) {
	panic("unimplemented")
}

// CreateTodo implements graph.MutationResolver.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.Todo, error) {
	panic("unimplemented")
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
