package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	graph "assignment/internal/graph/generate"
	"assignment/internal/graph/model"
	"context"
)

// Todos implements graph.QueryResolver.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic("unimplemented")
}

// User implements graph.QueryResolver.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return &model.User{ID: "1111"}, nil
}

// User implements graph.QueryResolver.
func (r *queryResolver) Users(ctx context.Context, filter model.UserFilterInput) ([]*model.User, error) {
	panic("not implemented")
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
