package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	graph "assignment/internal/graph/generate"
	model1 "assignment/internal/model"
	"context"
	"fmt"
)

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model1.Todo) (*model1.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Todo returns graph.TodoResolver implementation.
func (r *Resolver) Todo() graph.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
