// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type CreateTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Response struct {
	IsSuccess *bool   `json:"isSuccess,omitempty"`
	Message   *string `json:"message,omitempty"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID             string    `json:"id"`
	UsrName        *string   `json:"usr_name,omitempty"`
	UsrEmail       *string   `json:"usr_email,omitempty"`
	UsrPhone       *string   `json:"usr_phone,omitempty"`
	UsrSex         *string   `json:"usr_sex,omitempty"`
	UsrAvatar      *string   `json:"usr_avatar,omitempty"`
	UsrDateOfBirth *string   `json:"usr_date_of_birth,omitempty"`
	UsrRoles       []*string `json:"usr_roles,omitempty"`
	UsrStatus      *string   `json:"usr_status,omitempty"`
}

type UserFilterInput struct {
	UsrName  *string `json:"usr_name,omitempty"`
	UsrEmail *string `json:"usr_email,omitempty"`
}

type UserInput struct {
	UsrName        *string   `json:"usr_name,omitempty"`
	UsrEmail       *string   `json:"usr_email,omitempty"`
	UsrPhone       *string   `json:"usr_phone,omitempty"`
	UsrSex         *string   `json:"usr_sex,omitempty"`
	UsrAvatar      *string   `json:"usr_avatar,omitempty"`
	UsrDateOfBirth *string   `json:"usr_date_of_birth,omitempty"`
	UsrRoles       []*string `json:"usr_roles,omitempty"`
	UsrStatus      *string   `json:"usr_status,omitempty"`
}

type UserResponse struct {
	IsSuccess bool    `json:"isSuccess"`
	Message   *string `json:"message,omitempty"`
	User      *User   `json:"user,omitempty"`
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
)

var AllRole = []Role{
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
